# Generated by Django 4.2.7 on 2025-11-19 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientosolicitud',
            name='solicitud',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='tipo_solicitudes.solicitud'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tiposolicitud',
            name='responsable',
            field=models.CharField(choices=[('1', 'Control escolar'), ('2', 'Responsable de programa'), ('3', 'Responsable de tutorías'), ('4', 'Director')], default='1', max_length=1),
        ),
    ]
