# Generated by Django 4.2.7 on 2025-11-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_solicitudes', '0002_seguimientosolicitud_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estatus',
            field=models.CharField(choices=[('1', 'Creada'), ('2', 'En proceso'), ('3', 'Terminada'), ('4', 'Cancelada')], default='1', max_length=1),
        ),
    ]
