# Generated by Django 5.2.8 on 2025-11-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_solicitudes', '0004_remove_solicitud_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientosolicitud',
            name='fecha_terminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
